# baseURL = 'https://lilinascimento.github.io/SD-RP/'
baseURL = 'https://example.org/'
languageCode = 'en-us'
# languageCode = 'pt-br'
title = 'My New Hugo Site'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
